### ISSUE TITLE
跳转bugly失败

### ISSUE THREAD

**Issue by tinysheepyang** [jokinkuang/BuglyScrapy#1]
登录成功后台地址跳转到
https://graph.qq.com/oauth2.0/show?which=Login&display=pc&client_id=101481973&redirect_uri=https%3A%2F%2Fcas.bugly.qq.com%2Fcas%2FloginBack%3Ftype%3D9%26sn%3Ddd5bff1a-da91-46d4-bb7d-4e8fd07c0f84&response_type=code&state=e997d46ab447a05b1a1505f897f33f20&scope=get_user_info,add_topic,add_one_blog,add_album,upload_pic,list_album,add_share,check_page_fans,add_t,add_pic_t,del_t,get_repost_list,get_info,get_other_info,get_fanslist,get_idollist,add_idol,del_ido,get_tenpay_addr

**Comment by jeniva** [comment]
请问你后面有解决吗？我也遇到这个问题

**Comment by jokinkuang** [comment]
没用一段时间了，不知道现在还能不能登录。如果能登录成功，意味着已经顺利拿到session，那么直接访问其它bugly地址就行了。

**Comment by jeniva** [comment]
我现在执行时会提示账号异常，不知道是不是现在不能爬bugly了


![image](https://user-images.githubusercontent.com/8514029/66750917-55ac5680-eec0-11e9-8fd6-3abba60eb900.png)

**Comment by tinysheepyang** [comment]
后面用pyppeteer 解决的 ，另外qq每天次数登录过多会提示账号异常

**Comment by tinysheepyang** [comment]
后面用pyppeteer 解决的 ，另外qq每天次数登录过多会提示账号异常
